</$objtype/mkfile
#TARG=`{ls *.c | grep -v stubs\.c | sed -n '/\.c$/s/\.c$//p'}

COMMON=\
	../plan9/fs.$O\
	../plan9/nanosec.$O\
	../plan9/sys.$O\
	../plan9/threads.$O\
	../util/print.$O\
	stubs.$O\

HFILES=
</sys/src/cmd/mkmany
BIN=.

#LDFLAGS=$LDFLAGS -p

CFLAGS=$CFLAGS -p -D__plan9__ -D__${objtype}__ \
	-I/sys/include/npe \
	-I.. \
	-I../cmd -I../draw -I../fs -I../graph -I../index -I../lib \
	-I../layout -I../plan9 -I../rend -I../ui -I../util \

%.$O: %.c
	$CC $CFLAGS -o $target $stem.c

$O.fs_gfa:	fs_gfa.$O $COMMON ../fs/fs.$O
	$LD $LDFLAGS -o $target $prereq

$O.fs_gfa_em_new:	fs_gfa_em.$O $COMMON ../fs/fs.$O ../fs/em_new.$O
	$LD $LDFLAGS -o $target $prereq

$O.fs_gfa_em_hash:	fs_gfa_em.$O $COMMON ../fs/fs.$O ../fs/em.$O
	$LD $LDFLAGS -o $target $prereq
