</$objtype/mkfile
TARG=`{ls *.c | grep -v stubs\.c | sed -n '/\.c$/s/\.c$//p'}

OFILES=\
	../cmd/cmd.$O\
	../draw/color.$O\
	../graph/graph.$O\
	../fs/fs.$O\
	../fs/em.$O\
	../fs/index.$O\
	../fs/meta.$O\
	../plan9/awk.$O\
	../plan9/fs.$O\
	../plan9/sys.$O\
	../util/print.$O\
	stubs.$O\

HFILES=
</sys/src/cmd/mkmany
BIN=.

LDFLAGS=$LDFLAGS -p

CFLAGS=$CFLAGS -p -D__plan9__ -D__${objtype}__ \
	-I/sys/include/npe \
	-I.. \
	-I../cmd -I../draw -I../fs -I../graph -I../index -I../lib \
	-I../layout -I../plan9 -I../rend -I../ui -I../util \

%.$O: %.c
	$CC $CFLAGS -o $target $stem.c
