</$objtype/mkfile
TARG=`{ls | sed -n '/\.c$/s/\.c$//p'}

OFILES=\
	../graph/graph.$O\
	../fs/fs.$O\
	../fs/em.$O\
	../fs/index.$O\
	../plan9/fs.$O\
	../plan9/sys.$O\
	../util/print.$O\

HFILES=
</sys/src/cmd/mkmany
BIN=.

CFLAGS=$CFLAGS -p -D__plan9__ -D__${objtype}__ \
	-I/sys/include/npe \
	-I.. \
	-I../cmd -I../draw -I../fs -I../graph -I../index \
	-I../layout -I../plan9 -I../rend -I../ui -I../util \

%.$O: %.c
	$CC $CFLAGS -o $target $stem.c
