int	zoomgraph(Graph*, int);
void	expandnode(Graph*, Node*);
void	retractnode(Graph*, Node*);
Node*	getnode(Graph*, ssize);
Node*	getactivenode(Graph*, Node*);
Node*	str2node(Graph*, char*);
Edge*	getedge(Graph*, ssize);
int	ischild(Graph*, ssize, ssize);
Node*	touchnode(Graph*g, ssize id, ssize pid, ssize idx, int w);
Node*	pushnode(Graph*, ssize, ssize, ssize, int);
Node*	touchnode(Graph*g, ssize id, ssize pid, ssize idx, int w);
Node*	pushsibling(Graph*, ssize, Node*, ssize, int);
Node*	pushnamednode(Graph*, char*);
Node*	pushchild(Graph*, ssize, Node*, ssize, int);
Edge*	pushnamededge(Graph*, char*, char*, int, int);
Edge*	pushedge(Graph*, Node*, Node*, int, int);
void	poptree(Graph*, Node*);
void	printgraph(Graph*);
void	cleargraph(Graph*);
void	nukegraph(Graph*);
void	pushgraph(Graph);
void	lockgraphs(int);
void	unlockgraphs(int);
Graph	initgraph(int);
