int	zoomgraph(Graph*, int);
void	expandnode(Graph*, Node*);
void	retractnode(Graph*, Node*);
ioff	str2idx(char*);
ioff	getid(Graph*, char*);
ioff	pushnode(Graph*, char*);
ioff	pushedge(Graph*, char*, char*, int, int);
void	printgraph(Graph*);
void	cleargraphtempshit(Graph*);
void	nukegraph(Graph*);
void	pushgraph(Graph);
void	lockgraphs(int);
void	unlockgraphs(int);
Graph	initgraph(int);
