#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#define	SOKOL_IMPL
#define	SOKOL_NO_ENTRY
#include "lib/sokol_app.h"
#include "lib/sokol_gfx.h"
#include "lib/sokol_log.h"
#include "lib/sokol_glue.h"
#include "sokol_gfx_ext.h"
