char *awkprog = "BEGIN{\n"
"	black = 0x000000c0\n"
"	blue = 0x1f78b4c0\n"
"	bluegreen = 0x5fc69fc0\n"
"	brightblue = 0x0000ffc0\n"
"	brightgreen = 0x00ff00c0\n"
"	brightpurple = 0x00ffffc0\n"
"	brightred = 0xff0000c0\n"
"	brightyellow = 0xffff00c0\n"
"	brown = 0xb15928c0\n"
"	cyan = 0x7acdcdc0\n"
"	darkgray = 0x3f3f3fc0\n"
"	darkgreen = 0x33a02cc0\n"
"	darkpink = 0xc96088c0\n"
"	darkpurple = 0x6a3d9ac0\n"
"	gray = 0x777777c0\n"
"	green = 0x8ec65ec0\n"
"	greyblue = 0xbebadac0\n"
"	greybrown = 0x7f5f67c0\n"
"	greygreen = 0xccebc5c0\n"
"	greyred = 0xc76758c0\n"
"	lightblue = 0x80b1d3c0\n"
"	lightbrown = 0xca9560c0\n"
"	lightgray = 0xc0c0c0c0\n"
"	lightgreen = 0xd5f65fc0\n"
"	lightgrey = 0xd9d9d9c0\n"
"	lightorange = 0xfdb462c0\n"
"	lightpink = 0xfccde5c0\n"
"	lightpurple = 0xbc80bdc0\n"
"	lightred = 0xfb8072c0\n"
"	lightteal = 0x8dd3c7c0\n"
"	orange = 0xff7f00c0\n"
"	paleblue = 0xa6cee3c0\n"
"	palegray = 0xdcdcdcc0\n"
"	palegreen = 0xb2df8ac0\n"
"	paleorange = 0xfdbf6fc0\n"
"	palepurple = 0xc893f0c0\n"
"	palered = 0xfb9a99c0\n"
"	paleviolet = 0xcab2d6c0\n"
"	paleyellow = 0xffffb3c0\n"
"	purple = 0xb160c9c0\n"
"	purpleblue = 0x8080ffc0\n"
"	red = 0xe31a1cc0\n"
"	teal = 0x009696c0\n"
"	violet = purple\n"
"	white = 0xffffffc0\n"
"	yellow = 0xffed6fc0\n"
"	srand()\n"
"	OFS = \"\\t\"\n"
"}\n"
"function cmd(code){\n"
"	if(code == \"FHJ142\"){	# wing to proceed to targets\n"
"		if(++fnr == nd + 1)\n"
"			cmd(\"FGD135\")\n"
"		else{\n"
"			print deferred[fnr]\n"
"			loadbatch()\n"
"		}\n"
"	}else if(code == \"FGD135\"){	# wing attack plan R\n"
"		if(fnr < nd + 1)\n"
"			return\n"
"		crm114 = 1\n"
"		loadall()\n"
"		if(die)\n"
"			quit()\n"
"		if(noreset)\n"
"			print \"r\"\n"
"		else\n"
"			print \"R\"\n"
"		noreset = 0\n"
"	}else if(code == \"FJJ142\"){	# mission completed, returning\n"
"		die = 1\n"
"		cmd(\"FHJ142\")\n"
"	}else if(code == \"OPL753\"){	# wing to contact base immediately\n"
"		loadall()\n"
"		print \"R\"\n"
"	}\n"
"}\n"
"function exportlayout(f){\n"
"	print \"o\", f\n"
"}\n"
"function importlayout(f){\n"
"	if(crm114 == 1)\n"
"		print \"i\", f\n"
"	else{\n"
"		deferred[++nd] = \"i\\t\" f \"\\n\"\n"
"		noreset = 1\n"
"	}\n"
"}\n"
"function readcsv(f){\n"
"	if(crm114 == 1)\n"
"		print \"f\", f\n"
"	else\n"
"		deferred[++nd] = \"f\\t\" f \"\\n\"\n"
"}\n"
"function addnode(id, name, color){\n"
"	# remove placeholder for nodes spawned from out of order links\n"
"	if(id in label){\n"
"		delete node[label[id]]\n"
"		delete label[id]\n"
"	}\n"
"	node[name] = id\n"
"	label[id] = name\n"
"	if(color != \"\")\n"
"		CL[name] = color\n"
"}\n"
"function delnode(name){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	delete label[node[name]]\n"
"	delete node[name]\n"
"}\n"
"function checknodeid(id){\n"
"	if(!(id in label)){\n"
"		print \"E\\tno such nodeid: \" id\n"
"		return 0\n"
"	}\n"
"	return 1\n"
"}\n"
"function checknodename(name){\n"
"	if(!(name in node)){\n"
"		print \"E\\tno such node: \" name\n"
"		return 0\n"
"	}\n"
"	return 1\n"
"}\n"
"function edgeinfostr(i,	e, u, v, a, b, s){\n"
"	e = realedge(i)\n"
"	u = e >> 32\n"
"	v = e >> 2 & 0x3fffffff\n"
"	a = e & 1 ? \"-\" : \"+\"\n"
"	b = e & 2 ? \"-\" : \"+\"\n"
"	if(!checknodeid(u) || !checknodeid(v))\n"
"		return\n"
"	s = label[u] a label[v] b\n"
"	if(i in cigar)\n"
"		s = s \", CIGAR=\" cigar[i]\n"
"	return s\n"
"}\n"
"function edgeinfo(i, s){\n"
"	if((s = edgeinfostr(i)) == \"\")\n"
"		return\n"
"	info(\"Edge: \" s)\n"
"}\n"
"function findnode(name,	id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	id = node[name]\n"
"	selectnodebyid(id)\n"
"	print \"N\", id\n"
"}\n"
"function selinfostr(	id, name, l, n, m, s){\n"
"	if(length(selected) == 0)\n"
"		return \"\"\n"
"	l = 0\n"
"	s = \"\"\n"
"	n = m = 0\n"
"	for(id in selected){\n"
"		name = label[id]\n"
"		if(name in LN)\n"
"			l += LN[name]\n"
"		if(m < 28){\n"
"			m = length(s)\n"
"			s = s (m == 0 ? \"\" : \",\") name\n"
"		}else if(n == 0){\n"
"			n++\n"
"			s = s \",...\"\n"
"		}\n"
"	}\n"
"	s = \"Selected: \" s\n"
"	if(length(selected) == 1)\n"
"		return s \", length=\" l\n"
"	return s \"; total length=\" l \" in \" length(selected) \" nodes\"\n"
"}\n"
"function nodeinfo(id,	name, s){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	name = label[id]\n"
"	s = \"Node: \" name\n"
"	if(name in LN)\n"
"		s = s \", length=\" LN[name]\n"
"	info(s)\n"
"}\n"
"function deselect(	id){\n"
"	selinfo = \"\"\n"
"	for(id in selected)\n"
"		unshow(id, selected[id])\n"
"	delete selected\n"
"}\n"
"function deselectnodebyid(id,	col){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	if(!(id in selected)){\n"
"		print \"E\\tdeselect: not selected: \" id\n"
"		return\n"
"	}\n"
"	if(length(selected) == 1){\n"
"		deselect()\n"
"		return\n"
"	}\n"
"	col = selected[id]\n"
"	delete selected[id]\n"
"	selinfo = selinfostr()\n"
"	unshow(id, col)\n"
"}\n"
"function deselectnode(name,	id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	deselectnodebyid(node[name])\n"
"}\n"
"function showselected(){\n"
"	selinfo = selinfostr()\n"
"	refresh()\n"
"}\n"
"function selectnodebyid(id, noshow){\n"
"	if(!checknodeid(id) || id in selected)\n"
"		return\n"
"	selected[id] = CL[label[id]]\n"
"	if(!noshow)\n"
"		showselected()\n"
"}\n"
"function selectnode(name, id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	id = node[name]\n"
"	selectnodebyid(id)\n"
"}\n"
"function toggleselect(id){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	if(id in selected)\n"
"		deselectnodebyid(id)\n"
"	else\n"
"		selectnodebyid(id)\n"
"}\n"
"function reselectnode(id){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	deselect()\n"
"	selectnodebyid(id)\n"
"}\n"
"function initx(name, x){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	x0[name] = x\n"
"	print \"x\", node[name], x\n"
"}\n"
"function inity(name, y){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	y0[name] = y\n"
"	print \"y\", node[name], y\n"
"}\n"
"function fixx(name, x){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	fx[name] = x\n"
"	print \"X\", node[name], x\n"
"}\n"
"function fixy(name, y){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	fy[name] = y\n"
"	print \"Y\", node[name], y\n"
"}\n"
"function quit(){\n"
"	print \"!\"\n"
"}\n"
"# too complicated if nested, and temporary anyway; would ideally expand\n"
"# other tags into tag[i]\n"
"function subexpr(s, v, fn,	i, j, t, pred){\n"
"	i = match(s, \"\\][ 	]*=[^=]\")\n"
"	# error check: i not 0; only sub expression up to } or ; etc\n"
"	pred = substr(s, 1, i-1)\n"
"	s = substr(s, RSTART+RLENGTH-1)\n"
"	# my god man, implement pointers\n"
"	eval(\"{w = length(\" v \") == 0 ? \\\"node\\\" : v}\")\n"
"	$0 = \"for(i in \" w \") if(\" pred \"){ \" fn \"(i, \" s \")}\"\n"
"}\n"
"#crm114 && $1 == function\"{\n"
"#	eval($0)\n"
"#	next\n"
"#}\n"
"crm114 && /^[	 ]*[A-Za-z][A-Za-z0-9 ]*\\[.*\\] *= */{\n"
"	i = index($0, \"[\")\n"
"	v = substr($0, 1, i - 1)\n"
"	s = substr($0, i + 1)\n"
"	if(v == \"CL\" || v ~ /[Cc][Oo][Ll][Oo][Rr]/)\n"
"		subexpr(s, v, \"nodecolor\")\n"
"	else if(v == \"x0\")\n"
"		subexpr(s, v, \"initx\")\n"
"	else if(v == \"y0\")\n"
"		subexpr(s, v, \"inity\")\n"
"	else if(v == \"fx\")\n"
"		subexpr(s, v, \"fixx\")\n"
"	else if(v == \"fy\")\n"
"		subexpr(s, v, \"fixy\")\n"
"}\n"
"{\n"
"	eval(\"{\" $0 \"}\")\n"
"}\n";
