char *awkprog = "BEGIN{\n"
"	black = \"0x000000\"\n"
"	blue = \"0x1f78b4\"\n"
"	bluegreen = \"0x5fc69f\"\n"
"	brightblue = \"0x0000ff\"\n"
"	brightgreen = \"0x00ff00\"\n"
"	brightpurple = \"0x00ffff\"\n"
"	brightred = \"0xff0000\"\n"
"	brightyellow = \"0xffff00\"\n"
"	brown = \"0xb15928\"\n"
"	cyan = \"0x7acdcd\"\n"
"	darkgray = \"0x3f3f3f\"\n"
"	darkgreen = \"0x33a02c\"\n"
"	darkpink = \"0xc96088\"\n"
"	darkpurple = \"0x6a3d9a\"\n"
"	gray = \"0x777777\"\n"
"	green = \"0x8ec65e\"\n"
"	greyblue = \"0xbebada\"\n"
"	greybrown = \"0x7f5f67\"\n"
"	greygreen = \"0xccebc5\"\n"
"	greyred = \"0xc76758\"\n"
"	lightblue = \"0x80b1d3\"\n"
"	lightbrown = \"0xca9560\"\n"
"	lightgray = \"0xc0c0c0\"\n"
"	lightgreen = \"0xd5f65f\"\n"
"	lightgrey = \"0xd9d9d9\"\n"
"	lightorange = \"0xfdb462\"\n"
"	lightpink = \"0xfccde5\"\n"
"	lightpurple = \"0xbc80bd\"\n"
"	lightred = \"0xfb8072\"\n"
"	lightteal = \"0x8dd3c7\"\n"
"	orange = \"0xff7f00\"\n"
"	paleblue = \"0xa6cee3\"\n"
"	palegray = \"0xdcdcdc\"\n"
"	palegreen = \"0xb2df8a\"\n"
"	paleorange = \"0xfdbf6f\"\n"
"	palepurple = \"0xc893f0\"\n"
"	palered = \"0xfb9a99\"\n"
"	paleviolet = \"0xcab2d6\"\n"
"	paleyellow = \"0xffffb3\"\n"
"	purple = \"0xb160c9\"\n"
"	purpleblue = \"0x8080ff\"\n"
"	red = \"0xe31a1c\"\n"
"	teal = \"0x009696\"\n"
"	violet = purple\n"
"	white = \"0xffffff\"\n"
"	yellow = \"0xffed6f\"\n"
"	srand()\n"
"	OFS = \"\\t\"\n"
"}\n"
"function addnode(id, name, color){\n"
"	# remove placeholder for nodes spawned from out of order links\n"
"	if(id in label){\n"
"		delete node[label[id]]\n"
"		delete label[id]\n"
"	}\n"
"	node[name] = id\n"
"	label[id] = name\n"
"	if(color != \"\")\n"
"		CL[name] = color\n"
"}\n"
"function nodecolor(name, color){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	if(length(color) == 0){\n"
"		print \"E no such color for node: \" name\n"
"		return\n"
"	}\n"
"	CL[name] = color\n"
"	print \"c\", node[name], color\n"
"}\n"
"function delnode(name){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	delete label[node[name]]\n"
"	delete node[name]\n"
"}\n"
"function reorderedge(u, v, id,	name, oid, d1, d2){\n"
"	d1 = v & 2 ? \"-\" : \"+\"\n"
"	d2 = v & 1 ? \"-\" : \"+\"\n"
"	v >>= 2\n"
"	if(!checknodeid(u) || !checknodeid(v))\n"
"		return\n"
"	name = label[u] d1 label[v] d2\n"
"	oid = edge[name]\n"
"	ledge[oid] = ledge[id]\n"
"	edge[ledge[id]] = oid\n"
"	ledge[id] = name\n"
"	edge[name] = id\n"
"}\n"
"function addedge(id, name){\n"
"	edge[name] = id\n"
"	ledge[id] = name\n"
"}\n"
"function deledgebyid(id){\n"
"	if(!(name in edge)){\n"
"		print \"E no such edge: \" name\n"
"		return\n"
"	}\n"
"	delete edge[ledge[id]]\n"
"	delete ledge[id]\n"
"}\n"
"function deledge(u, urev, v, vrev){\n"
"	pair = u urev \"\\x1c\" v vrev\n"
"	if(!(pair in edge)){\n"
"		print \"E no such edge: \" u urev \",\" v vrev\n"
"		return\n"
"	}\n"
"	delete ledge[edge[pair]]\n"
"	delete edge[pair]\n"
"}\n"
"function cmd(code){\n"
"	if(code == \"FGD135\"){	# wing attack plan R\n"
"		if(!noreset && relayout)\n"
"			deferred = deferred \"R\\n\"\n"
"		if(deferred != \"\"){\n"
"			print deferred\n"
"			deferred = \"\"\n"
"		}\n"
"		crm114 = 1\n"
"	}else if(!crm114){\n"
"		if(code == \"FHJ142\")	# wing to proceed to targets\n"
"			relayout = 1\n"
"	}\n"
"}\n"
"function exportlayout(f){\n"
"	print \"o\", f\n"
"}\n"
"function importlayout(f){\n"
"	if(crm114 == 1)\n"
"		print \"i\", f\n"
"	else{\n"
"		deferred = deferred \"i\\t\" f \"\\n\"\n"
"		noreset = 1\n"
"	}\n"
"}\n"
"function readcsv(f){\n"
"	if(crm114 == 1)\n"
"		print \"f\", f\n"
"	else{\n"
"		deferred = deferred \"f\\t\" f \"\\n\"\n"
"		relayout = 1\n"
"	}\n"
"}\n"
"function checknodeid(id){\n"
"	if(!(id in label)){\n"
"		print \"E no such nodeid: \" id\n"
"		return 0\n"
"	}\n"
"	return 1\n"
"}\n"
"function checknodename(name){\n"
"	if(!(name in node)){\n"
"		print \"E no such node: \" name\n"
"		return 0\n"
"	}\n"
"	return 1\n"
"}\n"
"function edgeinfo(id,	s){\n"
"	name = ledge[id]\n"
"	s = name\n"
"	sub(\"\\x1c\", \" \", s)\n"
"	if(name in cigar)\n"
"		s = s \", CIGAR=\\\"\" cigar[name] \"\\\"\"\n"
"	print \"I\", \"Edge: \" s\n"
"}\n"
"function findnode(name,	id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	id = node[name]\n"
"	print \"N\", id\n"
"}\n"
"function selinfostr(	id, name, l, n, m, s){\n"
"	if(length(selected) == 0)\n"
"		return \"\"\n"
"	l = 0\n"
"	s = \"\"\n"
"	n = m = 0\n"
"	for(id in selected){\n"
"		name = label[id]\n"
"		if(name in LN)\n"
"			l += LN[name]\n"
"		if(m < 28){\n"
"			s = s (length(s) == 0 ? \"\" : \",\") name\n"
"			m = length(s)\n"
"		}else if(n == 0){\n"
"			n++\n"
"			s = s \",...\"\n"
"		}\n"
"	}\n"
"	if(length(selected) == 1)\n"
"		return s \", length=\" l\n"
"	return s \"; total length=\" l \" in \" length(selected) \" nodes\"\n"
"}\n"
"function nodeinfostr(id,	s){\n"
"	name = label[id]\n"
"	s = name\n"
"	if(name in LN)\n"
"		s = s \", length=\" LN[name]\n"
"	return s\n"
"}\n"
"function selinfo(){\n"
"	if(length(selected) != 0)\n"
"		print \"s\", selinfostr()\n"
"	#else\n"
"	#	print \"E bug: nothing selected\"\n"
"}\n"
"function nodeinfo(id,	name, s){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	print \"I\", \"Node: \" nodeinfostr(id)\n"
"}\n"
"function deselect(dontkill,	i){\n"
"	if(length(selected) == 0)\n"
"		return\n"
"	for(i in selected)\n"
"		print \"c\", i, CL[label[i]]\n"
"	delete selected\n"
"	if(!dontkill)\n"
"		print \"s\"\n"
"}\n"
"function deselectnodebyid(id){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	if(!(id in selected)){\n"
"		print \"E deselect: not selected: \" id\n"
"		return\n"
"	}\n"
"	if(length(selected) == 1){\n"
"		deselect()\n"
"		return\n"
"	}\n"
"	delete selected[id]\n"
"	print \"c\", id, CL[label[id]]\n"
"}\n"
"function deselectnode(name,	id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	deselectnodebyid(node[name])\n"
"}\n"
"function selectnodebyid(id,	name, s, l){\n"
"	if(!checknodeid(id) || id in selected)\n"
"		return\n"
"	selected[id] = 1\n"
"}\n"
"function selectnode(name, id){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	id = node[name]\n"
"	selectnodebyid(id)\n"
"}\n"
"function toggleselect(id){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	if(id in selected)\n"
"		deselectnodebyid(id)\n"
"	else\n"
"		selectnodebyid(id)\n"
"}\n"
"function reselectnode(id){\n"
"	if(!checknodeid(id))\n"
"		return\n"
"	deselect(1)\n"
"	selectnodebyid(id)\n"
"}\n"
"function initx(name, x){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	x0[name] = x\n"
"	print \"x\", node[name], x\n"
"}\n"
"function inity(name, y){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	y0[name] = y\n"
"	print \"y\", node[name], y\n"
"}\n"
"function fixx(name, x){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	fx[name] = x\n"
"	print \"X\", node[name], x\n"
"}\n"
"function fixy(name, y){\n"
"	if(!checknodename(name))\n"
"		return\n"
"	fy[name] = y\n"
"	print \"Y\", node[name], y\n"
"}\n"
"function quit(){\n"
"	print \"!\"\n"
"}\n"
"# too complicated if nested, and temporary anyway; would ideally expand\n"
"# other tags into tag[i]\n"
"function subexpr(s, v, fn,	i, j, t, pred){\n"
"	i = match(s, \"\\][ 	]*=[^=]\")\n"
"	# error check: i not 0; only sub expression up to } or ; etc\n"
"	pred = substr(s, 1, i-1)\n"
"	s = substr(s, RSTART+RLENGTH-1)\n"
"	# my god man, implement pointers\n"
"	eval(\"{w = length(\" v \") == 0 ? \\\"node\\\" : v}\")\n"
"	$0 = \"for(i in \" w \") if(\" pred \"){ \" fn \"(i, \" s \")}\"\n"
"}\n"
"#crm114 && $1 == function\"{\n"
"#	eval($0)\n"
"#	next\n"
"#}\n"
"crm114 && /^[	 ]*[A-Za-z][A-Za-z0-9 ]*\\[.*\\] *= */{\n"
"	i = index($0, \"[\")\n"
"	v = substr($0, 1, i - 1)\n"
"	s = substr($0, i + 1)\n"
"	if(v == \"CL\" || v ~ /[Cc][Oo][Ll][Oo][Rr]/)\n"
"		subexpr(s, v, \"nodecolor\")\n"
"	else if(v == \"x0\")\n"
"		subexpr(s, v, \"initx\")\n"
"	else if(v == \"y0\")\n"
"		subexpr(s, v, \"inity\")\n"
"	else if(v == \"fx\")\n"
"		subexpr(s, v, \"fixx\")\n"
"	else if(v == \"fy\")\n"
"		subexpr(s, v, \"fixy\")\n"
"}\n"
"{\n"
"	eval(\"{\" $0 \"}\")\n"
"}\n";
