char *awkprog = "BEGIN{\n"
"	red = \"0xff000090\"\n"
"	green = \"0x00ff0090\"\n"
"	blue = \"0x0000ff90\"\n"
"	orange = \"0xffff0090\"\n"
"	yellow = \"0xff7f0090\"\n"
"	grey = \"0xffff0090\"\n"
"	brown = \"0x7f3f0090\"\n"
"	black = \"0x090\"\n"
"	white = \"0xffffff90\"\n"
"	lightblue = \"0x1f78b490\"\n"
"	lightorange = \"0xff7f0090\"\n"
"	lightgreen = \"0x33a02c90\"\n"
"	lightred = \"0xe31a1c90\"\n"
"	violet = \"0x6a3d9a90\"\n"
"	purple = violet\n"
"	lightbrown = \"0xb1592890\"\n"
"	paleblue = \"0x8080ff90\"\n"
"	palegreen = \"0x8ec65e90\"\n"
"	palered = \"0xc7675890\"\n"
"	paleorange = \"0xca956090\"\n"
"	paleviolet = \"0xc893f090\"\n"
"	greybrown = \"0x7f5f6790\"\n"
"	lightviolet = \"0xb160c990\"\n"
"	palebluegreen = \"0x5fc69f90\"\n"
"	pinkviolet = \"0xc9608890\"\n"
"	cyan = \"0x8dd3c790\"\n"
"	paleyellow = \"0xffffb390\"\n"
"	greyblue = \"0xbebada90\"\n"
"	lightorange2 = \"0xfb807290\"\n"
"	lightblue2 = \"0x80b1d390\"\n"
"	lightorange2 = \"0xfdb46290\"\n"
"	lightgreen2 = \"0xb3de6990\"\n"
"	greypink = \"0xfccde590\"\n"
"	lightgrey = \"0xd9d9d990\"\n"
"	lightviolet = \"0xbc80bd90\"\n"
"	greygreen = \"0xccebc590\"\n"
"	lightyellow = \"0xffed6f90\"\n"
"	lightblue2 = \"0xa6cee390\"\n"
"	lightgreen3 = \"0xb2df8a90\"\n"
"	lightpink = \"0xfb9a9990\"\n"
"	lightorange3 = \"0xfdbf6f90\"\n"
"	greyviolet = \"0xcab2d690\"\n"
"	paleyellow = \"0xffff9990\"\n"
"}\n"
"function addnode(id, name, color){\n"
"	# remove placeholder for nodes spawned from out of order links\n"
"	if(id in lnode){\n"
"		delete node[lnode[id]]\n"
"		delete lnode[id]\n"
"	}\n"
"	node[name] = id\n"
"	lnode[id] = name\n"
"	if(color != \"\")\n"
"		CL[name] = color\n"
"}\n"
"function nodecolor(name, color){\n"
"	if(!(name in node)){\n"
"		print \"E no such node\", name\n"
"		return\n"
"	}\n"
"	CL[name] = color\n"
"	print \"c\", node[name], color\n"
"}\n"
"function delnode(name){\n"
"	if(!(name in node)){\n"
"		print \"E no such node\", name\n"
"		return\n"
"	}\n"
"	delete lnode[node[name]]\n"
"	delete node[name]\n"
"}\n"
"function addedge(id, name){\n"
"	edge[name] = id\n"
"	ledge[id] = name\n"
"}\n"
"function deledgebyid(id){\n"
"	if(!(name in edge)){\n"
"		print \"E no such edge\", name\n"
"		return\n"
"	}\n"
"	delete edge[ledge[id]]\n"
"	delete ledge[id]\n"
"}\n"
"function deledge(u, urev, v, vrev){\n"
"	pair = u urev \"\\x1c\" v vrev\n"
"	if(!(pair in edge)){\n"
"		print \"E no such edge\", u urev \",\" v vrev\n"
"		return\n"
"	}\n"
"	delete ledge[edge[pair]]\n"
"	delete edge[pair]\n"
"}\n"
"function cmd(code){\n"
"	if(code == \"FGD135\"){	# wing attack plan R\n"
"		if(deferred != \"\"){\n"
"			print deferred\n"
"			deferred = \"\"\n"
"		}\n"
"		crm114 = 1\n"
"	}else if(code == \"KDH037\")	# all planes to report position\n"
"		standby++\n"
"	else if(code == \"OPL753\")	# wing to contact base immediately\n"
"		deferred = deferred \"R\\n\"\n"
"	else if(code == \"FJJ142\"){	# mission completed returning\n"
"		if(--standby == 0)\n"
"			print \"R\"\n"
"	}\n"
"	#else if(code == \"FHJ142\")	# wing to proceed to targets\n"
"	#else if(code == \"OPL753\")	# wing to contact base immediately\n"
"}\n"
"function exportlayout(f){\n"
"	print \"o\", f\n"
"}\n"
"function importlayout(f){\n"
"	if(crm114 == 1)\n"
"		print \"i\", f\n"
"	else{\n"
"		deferred = deferred \"i \" f \"\\n\"\n"
"		cmd(\"KDH037\")\n"
"	}\n"
"}\n"
"function readcsv(f){\n"
"	if(crm114 == 1)\n"
"		print \"f\", f\n"
"	else{\n"
"		deferred = deferred \"f \" f \"\\n\"\n"
"		cmd(\"KDH037\")\n"
"	}\n"
"}\n"
"function selectnode(){\n"
"}\n"
"function selectedge(){\n"
"}\n"
"# FIXME: stupid\n"
"function fixnode(name, x, y){\n"
"	if(!(name in node)){\n"
"		print \"E no such node\", name\n"
"		return\n"
"	}\n"
"	if(y == \"\")\n"
"		y = 0\n"
"	fx[name] = x\n"
"	fy[name] = y\n"
"	print \"X\", node[name], x, y\n"
"}\n"
"function fixnodex(name, x){\n"
"	if(!(name in node)){\n"
"		print \"E no such node\", name\n"
"		return\n"
"	}\n"
"	BO[name] = x\n"
"	print \"x\", node[name], x\n"
"}\n"
"{\n"
"	eval(\"{\" $0 \"}\")\n"
"}\n";
