char *bezier_geomsh = \
	"#version 430\n"
	"layout(lines) in;\n"
	"layout(triangle_strip, max_vertices=6) out;\n"
	"uniform mat4 mvp;\n"
	"const float thicc = 1.0;\n"
	"void\n"
	"main(){\n"
	"	/* FIXME: need to offset vertices for a proper miter, but there's no\n"
	"	 * way to know where the next segment lies; allegedly solvable by\n"
	"	 * using 6 control points instead of 4??\n"
	"	 */\n"
	"	vec2 n = normalize(gl_in[1].gl_Position.xy - gl_in[0].gl_Position.xy);\n"
	"	vec4 cw = mvp * vec4(thicc * vec2(n.y, -n.x), 0.0, 0.0);\n"
	"	gl_Position = gl_in[1].gl_Position + cw;\n"
	"	EmitVertex();\n"
	"	gl_Position = gl_in[0].gl_Position + cw;\n"
	"	EmitVertex();\n"
	"	gl_Position = gl_in[0].gl_Position - cw;\n"
	"	EmitVertex();\n"
	"	EndPrimitive();\n"
	"	gl_Position = gl_in[0].gl_Position - cw;\n"
	"	EmitVertex();\n"
	"	gl_Position = gl_in[1].gl_Position - cw;\n"
	"	EmitVertex();\n"
	"	gl_Position = gl_in[1].gl_Position + cw;\n"
	"	EmitVertex();\n"
	"	EndPrimitive();\n"
	"}\n";
