char *node_vertsh = \
	"#version 430\n"
	"//precision mediump float;\n"
	"precision lowp float;\n"
	"uniform mat4 mvp;\n"
	"uniform vec2 s;\n"
	"layout(location=0) in vec2 geom;\n"
	"layout(location=1) in vec2 pos;\n"
	"layout(location=2) in vec3 col0;\n"
	"layout(location=3) in float theta;\n"
	"layout(location=4) in uint idx0;\n"
	"out vec3 col;\n"
	"flat out uint idx;\n"
	"vec2 rotatez(vec2 v, float angle){\n"
	"	float s = sin(angle);\n"
	"	float c = cos(angle);\n"
	"	//return mat3(c, -s, 0.0, s, c, 0.0, 0.0, 0.0, 1.0) * v;\n"
	"	return mat2(c, -s, s, c) * v;\n"
	"}\n"
	"void main(){\n"
	"	float z = gl_InstanceID * 0.000001;\n"
	"	gl_Position = mvp * vec4((rotatez(geom, theta) + pos) / s, z, 1.0);\n"
	"	col = col0;\n"
	"	idx = idx0;\n"
	"	//idx = uint(gl_InstanceID);\n"
	"}\n";
