char *node_vertsh = \
	"#version 430\n"
	"//precision mediump float;\n"
	"precision lowp float;\n"
	"uniform mat4 mvp;\n"
	"layout(location=0) in vec2 geom;\n"
	"layout(location=1) in vec3 pos;\n"
	"layout(location=2) in vec3 dir;\n"
	"layout(location=3) in vec4 col0;\n"
	"layout(location=4) in float len;\n"
	"out vec4 col;\n"
	"vec2 rotatez(vec2 v, float c, float s){\n"
	"	return mat2(c, s, -s, c) * v;\n"
	"}\n"
	"void main(){\n"
	"	vec2 g = geom * vec2(len, 1.0);\n"
	"	vec3 r = vec3(rotatez(g, dir.x, dir.y), 0.0);\n"
	"	gl_Position = mvp * vec4(r + pos, 1.0);\n"
	"	col = col0;\n"
	"}\n";
