name: Makefile CI
on:
  push:
    branches: [main]
    paths: ['**.c','**.h']
  workflow_dispatch:
jobs:
  linux:
    name: linux
    strategy:
      matrix:
        #os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt-get install -y libbsd0 libgl-dev libglvnd-dev libglx-dev libmd0 libx11-dev libxau-dev libxcb1-dev libxcursor-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev
    - name: build
      env:
        CFLAGS: -mtune=native -O3 -pipe
      run: make -j 4
    - name: test
      run: ./strangepg -D load test/frag10.gfa
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: strangepg-${{ matrix.os }}
        path: strangepg
        overwrite: true
  mac:
    name: mac
    strategy:
      matrix:
        #os: [macos-15, macos-14, macos-13]
        os: [macos-15, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make -j 3
    - name: test
      run: ./strangepg -D load test/frag10.gfa
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: strangepg-${{ matrix.os }}
        path: strangepg
        overwrite: true
  win64:
    name: win64
    strategy:
      matrix:
        #os: [windows-2022, windows-2019]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: build
      env:
        CFLAGS: -mtune=native -O3 -pipe
        CC: gcc
      run: make TARGET=Win64 -j 4
    #- name: test
    #  run: ./strangepg -D load test/frag10.gfa
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: strangepg-${{ matrix.os }}
        path: strangepg.exe
        overwrite: true
  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: retrieve
      uses: actions/download-artifact@v4
      with:
        path: release
        pattern: strangepg-*
        merge-multiple: true
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
